language: node_js
node_js: '7.6'
sudo: enabled
dist: trusty
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libc6-dev-i386
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - linux-libc-dev:i386
      - linux-libc-dev
      - icns2png

before_install:
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then yarn run build:darwin:p ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then yarn run build:linux:p  ;fi
